### ISSUE TITLE
Decrease the memory requirement

### ISSUE THREAD

**Issue by CsatiZoltan** [kakearney/spycolor-pkg#1]
Previously, I did it with `imagesc(A)`.
I admit that your solution is easier to perceive. However, the memory requirement is HUGE. This is due to the fact that you create dense matrices even if one provides a sparse matrix. Unfortunately, it makes the code unusable for medium/large matrices. Could you somehow decrease the memory requirement?

**Comment by kakearney** [comment]
You're right, lazy coding on my part... Shouldn't be difficult to switch to sparse-friendly alternatives, so I'll do that as soon as I get a chance.

**Comment by CsatiZoltan** [comment]
Any progress? If you have no time, I am ready to implement it if you give me some hint which part of the code I should focus on.

**Comment by kakearney** [comment]
I just pushed an update that should address this.  Please reopen this issue if you find any problems with the new version.
